# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20200530_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(),
        ),
    ]
