# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='prof.Profile'),
            preserve_default=False,
        ),
    ]
