# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 3, 50, 0, 733349, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='prof.Profile'),
            preserve_default=False,
        ),
    ]
