# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20200603_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, blank=True, to='prof.Profile'),
            preserve_default=False,
        ),
    ]
