# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_auto_20200603_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pub_time']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/smiley-4832482_1920.png', null=True, upload_to='images/'),
        ),
    ]
