# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_auto_20201208_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=50),
        ),
    ]
